spring:
  application:
    name: document-service

  datasource:
    url: jdbc:postgresql://localhost:5435/document_db
    username: document_user
    password: document_pass

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: document-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

server:
  port: 8083