spring:
  application:
    name: document-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/credit-calculator}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/credit-calculator/protocol/openid-connect/certs}

  datasource:
    url: ${DOCUMENT_DB_URL:jdbc:postgresql://localhost:5435/document_db}
    username: ${DOCUMENT_DB_USERNAME:document_user}
    password: ${DOCUMENT_DB_PASSWORD:document_pass}

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: document-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

server:
  port: 8083

document:
  internal:
    api-key: ${DOCUMENT_INTERNAL_API_KEY:local-document-internal-api-key}
