[versions]
java = "21"
spring-boot = "3.2.5"
spring-dependency-management = "1.1.4"
spring-cloud = "2023.0.1"
postgresql = "42.7.3"
liquibase = "4.27.0"
openhtmltopdf = "1.0.10"
jackson-xml = "2.17.1"
testcontainers = "1.19.8"
awaitility = "4.2.1"

[libraries]
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
liquibase-core = { module = "org.liquibase:liquibase-core", version.ref = "liquibase" }
jackson-dataformat-xml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-xml", version.ref = "jackson-xml" }
openhtmltopdf-pdfbox = { module = "com.openhtmltopdf:openhtmltopdf-pdfbox", version.ref = "openhtmltopdf" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
testcontainers-kafka = { module = "org.testcontainers:kafka", version.ref = "testcontainers" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }