apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: credit-calculator-prod

commonLabels:
  environment: prod

patchesStrategicMerge:
  - replica-patch.yaml
