spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false
      routes:
        - id: application-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/applications/**
          filters:
            - AddRequestHeader=X-Forwarded-Prefix, /api
            - AddRequestHeader=X-Debug-Auth, allow


        - id: document-download
          uri: http://localhost:8081
          predicates:
            - Path=/api/documents/**
          filters:
            - AddRequestHeader=X-Forwarded-Prefix, /api
            - AddRequestHeader=X-Debug-Auth, allow

        - id: application-service-actuator
          uri: http://localhost:8081
          predicates:
            - Path=/application-service/actuator/**
          filters:
            - StripPrefix=1

        - id: scoring-service-actuator
          uri: http://localhost:8082
          predicates:
            - Path=/scoring-service/actuator/**
          filters:
            - StripPrefix=1

        - id: document-service-actuator
          uri: http://localhost:8083
          predicates:
            - Path=/document-service/actuator/**
          filters:
            - StripPrefix=1

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/credit-calculator
          jwk-set-uri: http://localhost:8180/realms/credit-calculator/protocol/openid-connect/certs

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

management.endpoint.health:
  probes:
    enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG

auth:
  keycloak:
    base-url: http://localhost:8180
    realm: credit-calculator
    client-id: credit-calculator-app
    admin-username: admin
    admin-password: admin
