apiVersion: v1
kind: ConfigMap
metadata:
  name: application-service-config
data:
  database-url: "jdbc:postgresql://postgres-application:5432/application_db"
  kafka-bootstrap-servers: "kafka:9092"
  scoring-base-url: "http://scoring-service:8082"
  document-base-url: "http://document-service:8083"
