### save in db
POST http://localhost:8081/api/applications/1adfa8a4-9763-4cc7-9a97-0f2331aaac95/submit
Content-Type: application/json

{
  "insuranceEnabled": true,
  "salaryClient": true,
  "gender": "MALE",
  "maritalStatus": "MARRIED",
  "dependentAmount": 0,
  "passportIssueDate": "2015-06-10",
  "passportIssueBranch": "UFMS TEST",
  "accountNumber": "40702810900000000001",
  "employment": {
    "employmentStatus": "EMPLOYED",
    "employerInn": "7701234567",
    "salary": 120000.00,
    "position": "MID_MANAGER",
    "workExperienceTotal": 60,
    "workExperienceCurrent": 24
  }
}
