spring:
  application:
    name: application-service
  datasource:
    url: jdbc:postgresql://localhost:5433/application_db
    username: application_user
    password: application_pass
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

management.endpoint.health:
  probes:
    enabled: true

integration:
  scoring:
    base-url: http://localhost:8082
  document:
    base-url: http://localhost:8083