spring:
  application:
    name: application-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/credit-calculator}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/credit-calculator/protocol/openid-connect/certs}
  datasource:
    url: ${APPLICATION_DB_URL:jdbc:postgresql://localhost:5433/application_db}
    username: ${APPLICATION_DB_USERNAME:application_user}
    password: ${APPLICATION_DB_PASSWORD:application_pass}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

management.endpoint.health:
  probes:
    enabled: true

integration:
  scoring:
    base-url: ${SCORING_SERVICE_URL:http://localhost:8082}
  document:
    base-url: ${DOCUMENT_SERVICE_URL:http://localhost:8083}
    internal-api-key: ${DOCUMENT_INTERNAL_API_KEY:local-document-internal-api-key}
